name: release docker image

on:
  release:
    types: [published]

jobs:
  build:
    name: Build + Publish Container Image
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    -
      # this is due to error repository name must be lowercase, and github actions cannot lower it
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/${{ github.repository_owner }}/ciinabox-ecs
        tags: |
          type=raw,value=${{ github.event.release.tag_name }},priority=1000
          type=raw,value=latest
    
    - name: Login to  GitHub Container Repository
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Container Image to GitHub Container Repository
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        build-args: CIINABOX_ECS_VERSION=${{ github.event.release.tag_name }}
